### ISSUE TITLE
DFD Comments - Sept 19

### ISSUE THREAD

**Issue by germonprez** [SunweiWang/ISQA-3420Assignment1#13]
Hi Sunwei,

A few DFD comments: 

1) Be very descriptive in your model. For example, Results is not a very descriptive dataflow. In that part of the model better dataflow labels could be: 

a) Request to Browse Results --rewritten as--> All Software Package and License Information Request

b) Results --rewritten as--> All Software Package and License Information Result

c) Browser Results --rewritten as--> Query Software Package and License Datastore to Retrieve Results for Browsing

From a developer perspective, the latter ones are much more helpful and clear. 

Regarding the DFD Dictionary, you are correct. You would create a dictionary for EVERY item in your DFD. Each item would contain a simple, one sentence definition of the item. As an example: 

a) Query Software Package and License Datastore to Receive Results for Browsing: This process is responsible for managing the connection between the Manager and the datastore. This process is responsible for retrieving all software package and license information and returning it to the Manager. 

I hope these help! 

Matt

**Comment by SunweiWang** [comment]
Thank you for your detailed explanation.

I have corrected my DFD as following, and I will create a issue regarding to DFD Dictionary and improve it over time.

![dfd_9_19](https://cloud.githubusercontent.com/assets/9740504/18648579/dc519b0e-7e80-11e6-9807-397c88335cb1.png)

**Comment by germonprez** [comment]
Looks much better. You may want to consider names for OSS Components as well. Be explicit.

**Comment by SunweiWang** [comment]
Okay, I have change the name for OSS Components to be more explicit
![dfd_9_19 1](https://cloud.githubusercontent.com/assets/9740504/18683625/a3433a3c-7f36-11e6-9632-a0c41cd81ed7.png)

**Comment by germonprez** [comment]
Looks good. Very clear and descriptive.
