### ISSUE TITLE
DFD Comments #2

### ISSUE THREAD

**Issue by germonprez** [SunweiWang/ISQA-3420Assignment1#7]
I think that this part of the DFD: 

<img width="233" alt="screen shot 2016-09-09 at 12 30 09 pm" src="https://cloud.githubusercontent.com/assets/656208/18396438/33e7eb16-7689-11e6-9cb3-83fbd92fe478.png">

Can be removed. You can just go from Identify OSS Components to the Datastore

**Comment by SunweiWang** [comment]
Thanks, this helps me simplify my DFD.
